#!/usr/bin/python
from Tkinter import *
a=Tk()
t=Frame(a)
t1=Frame(a)
a=Button(t,text="button")
a1=Button(t,text="buttonnnn")
a2=Button(t,text="buttonnnnn")
a3=Button(t,text="button")
a4=Button(t1,text="button")
e=Entry(t)
e1=Entry(t)
e2=Entry(t)
e3=Entry(t)
a.grid(row=0,column=0,sticky='we',padx=2,pady=2)
a1.grid(row=1,column=0,sticky='we',padx=2,pady=2)
a2.grid(row=2,column=0,sticky='we',padx=2,pady=2)
a3.grid(row=3,column=0,sticky='we',padx=2,pady=2)
e.grid(row=0,column=1,padx=2,pady=2)
e1.grid(row=1,column=1,padx=2,pady=2)
e2.grid(row=2,column=1,padx=2,pady=2)
e3.grid(row=3,column=1,padx=2,pady=2)
a4.pack(padx=2,pady=2)
t.pack()
t1.pack()

mainloop()
